spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    password: root123
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 20
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${user.dir}/src/main/resources/static/
    mvc:
      static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${user.dir}/src/main/resources/static/images
  file:
    upload-dir: classpath:static/images
logging:
  level:
    root: INFO
    uz.pdp.project: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.validation: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
springdoc:
  swagger-ui:
    path: "/ui"
